/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Standup API
 * API do serviço de geração, revisão e publicação de standups.
 * OpenAPI spec version: 0.0.1
 */
import { HttpClient } from '@angular/common/http';

import { inject } from '@angular/core';

import { injectMutation } from '@tanstack/angular-query-experimental';
import type {
  CreateMutationOptions,
  CreateMutationResult,
  MutationFunction,
} from '@tanstack/angular-query-experimental';

import { fromEvent, lastValueFrom } from 'rxjs';

import { takeUntil } from 'rxjs/operators';

import type { TriggerAcceptedDto } from '../../model';

function filterParams(
  params: Record<string, unknown>,
  requiredNullableKeys: Set<string> = new Set(),
): Record<string, string | number | boolean | Array<string | number | boolean>> {
  const filteredParams: Record<
    string,
    string | number | boolean | null | Array<string | number | boolean>
  > = {};
  for (const [key, value] of Object.entries(params)) {
    if (Array.isArray(value)) {
      const filtered = value.filter(
        (item) =>
          item != null &&
          (typeof item === 'string' || typeof item === 'number' || typeof item === 'boolean'),
      ) as Array<string | number | boolean>;
      if (filtered.length) {
        filteredParams[key] = filtered;
      }
    } else if (value === null && requiredNullableKeys.has(key)) {
      filteredParams[key] = value;
    } else if (
      value != null &&
      (typeof value === 'string' || typeof value === 'number' || typeof value === 'boolean')
    ) {
      filteredParams[key] = value as string | number | boolean;
    }
  }
  return filteredParams as Record<
    string,
    string | number | boolean | Array<string | number | boolean>
  >;
}
/**
 * @summary Dispara a geração manual do digest semanal
 */
export const triggerDigest = (
  http: HttpClient,
  options?: { signal?: AbortSignal | null },
): Promise<TriggerAcceptedDto> => {
  const url = `/digests/trigger`;
  const request$ = http.post<TriggerAcceptedDto>(url, undefined);
  if (options?.signal) {
    return lastValueFrom(request$.pipe(takeUntil(fromEvent(options.signal, 'abort'))));
  }
  return lastValueFrom(request$);
};

export const getTriggerDigestMutationOptions = <TError = unknown, TContext = unknown>(
  http: HttpClient,
  options?: {
    mutation?: CreateMutationOptions<
      Awaited<ReturnType<typeof triggerDigest>>,
      TError,
      void,
      TContext
    >;
    fetch?: RequestInit;
  },
): CreateMutationOptions<Awaited<ReturnType<typeof triggerDigest>>, TError, void, TContext> => {
  const mutationKey = ['triggerDigest'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof triggerDigest>>, void> = () => {
    return triggerDigest(http, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type TriggerDigestMutationResult = NonNullable<Awaited<ReturnType<typeof triggerDigest>>>;

export type TriggerDigestMutationError = unknown;

/**
 * @summary Dispara a geração manual do digest semanal
 */
export const injectTriggerDigest = <TError = unknown, TContext = unknown>(options?: {
  mutation?: CreateMutationOptions<
    Awaited<ReturnType<typeof triggerDigest>>,
    TError,
    void,
    TContext
  >;
  fetch?: RequestInit;
}): CreateMutationResult<Awaited<ReturnType<typeof triggerDigest>>, TError, void, TContext> => {
  const http = inject(HttpClient);
  const triggerDigestMutationOptions = getTriggerDigestMutationOptions(http, options);

  return injectMutation(() => triggerDigestMutationOptions);
};
