/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Standup API
 * API do serviço de geração, revisão e publicação de standups.
 * OpenAPI spec version: 0.0.1
 */
import { HttpClient } from '@angular/common/http';

import { inject } from '@angular/core';

import { injectMutation } from '@tanstack/angular-query-experimental';
import type {
  CreateMutationOptions,
  CreateMutationResult,
  MutationFunction,
} from '@tanstack/angular-query-experimental';

import { fromEvent, lastValueFrom } from 'rxjs';

import { takeUntil } from 'rxjs/operators';

import type {
  CancelTodayReminderResponseDto,
  SnoozeReminderResponseDto,
  TriggerAcceptedDto,
} from '../../model';

function filterParams(
  params: Record<string, unknown>,
  requiredNullableKeys: Set<string> = new Set(),
): Record<string, string | number | boolean | Array<string | number | boolean>> {
  const filteredParams: Record<
    string,
    string | number | boolean | null | Array<string | number | boolean>
  > = {};
  for (const [key, value] of Object.entries(params)) {
    if (Array.isArray(value)) {
      const filtered = value.filter(
        (item) =>
          item != null &&
          (typeof item === 'string' || typeof item === 'number' || typeof item === 'boolean'),
      ) as Array<string | number | boolean>;
      if (filtered.length) {
        filteredParams[key] = filtered;
      }
    } else if (value === null && requiredNullableKeys.has(key)) {
      filteredParams[key] = value;
    } else if (
      value != null &&
      (typeof value === 'string' || typeof value === 'number' || typeof value === 'boolean')
    ) {
      filteredParams[key] = value as string | number | boolean;
    }
  }
  return filteredParams as Record<
    string,
    string | number | boolean | Array<string | number | boolean>
  >;
}
/**
 * @summary Adia o lembrete do standup do dia
 */
export const snoozeReminder = (
  http: HttpClient,
  options?: { signal?: AbortSignal | null },
): Promise<SnoozeReminderResponseDto> => {
  const url = `/reminders/snooze`;
  const request$ = http.post<SnoozeReminderResponseDto>(url, undefined);
  if (options?.signal) {
    return lastValueFrom(request$.pipe(takeUntil(fromEvent(options.signal, 'abort'))));
  }
  return lastValueFrom(request$);
};

export const getSnoozeReminderMutationOptions = <TError = unknown, TContext = unknown>(
  http: HttpClient,
  options?: {
    mutation?: CreateMutationOptions<
      Awaited<ReturnType<typeof snoozeReminder>>,
      TError,
      void,
      TContext
    >;
    fetch?: RequestInit;
  },
): CreateMutationOptions<Awaited<ReturnType<typeof snoozeReminder>>, TError, void, TContext> => {
  const mutationKey = ['snoozeReminder'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof snoozeReminder>>, void> = () => {
    return snoozeReminder(http, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type SnoozeReminderMutationResult = NonNullable<Awaited<ReturnType<typeof snoozeReminder>>>;

export type SnoozeReminderMutationError = unknown;

/**
 * @summary Adia o lembrete do standup do dia
 */
export const injectSnoozeReminder = <TError = unknown, TContext = unknown>(options?: {
  mutation?: CreateMutationOptions<
    Awaited<ReturnType<typeof snoozeReminder>>,
    TError,
    void,
    TContext
  >;
  fetch?: RequestInit;
}): CreateMutationResult<Awaited<ReturnType<typeof snoozeReminder>>, TError, void, TContext> => {
  const http = inject(HttpClient);
  const snoozeReminderMutationOptions = getSnoozeReminderMutationOptions(http, options);

  return injectMutation(() => snoozeReminderMutationOptions);
};
/**
 * @summary Cancela o lembrete do dia atual
 */
export const cancelTodayReminder = (
  http: HttpClient,
  options?: { signal?: AbortSignal | null },
): Promise<CancelTodayReminderResponseDto> => {
  const url = `/reminders/cancel-today`;
  const request$ = http.post<CancelTodayReminderResponseDto>(url, undefined);
  if (options?.signal) {
    return lastValueFrom(request$.pipe(takeUntil(fromEvent(options.signal, 'abort'))));
  }
  return lastValueFrom(request$);
};

export const getCancelTodayReminderMutationOptions = <TError = unknown, TContext = unknown>(
  http: HttpClient,
  options?: {
    mutation?: CreateMutationOptions<
      Awaited<ReturnType<typeof cancelTodayReminder>>,
      TError,
      void,
      TContext
    >;
    fetch?: RequestInit;
  },
): CreateMutationOptions<
  Awaited<ReturnType<typeof cancelTodayReminder>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ['cancelTodayReminder'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof cancelTodayReminder>>,
    void
  > = () => {
    return cancelTodayReminder(http, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CancelTodayReminderMutationResult = NonNullable<
  Awaited<ReturnType<typeof cancelTodayReminder>>
>;

export type CancelTodayReminderMutationError = unknown;

/**
 * @summary Cancela o lembrete do dia atual
 */
export const injectCancelTodayReminder = <TError = unknown, TContext = unknown>(options?: {
  mutation?: CreateMutationOptions<
    Awaited<ReturnType<typeof cancelTodayReminder>>,
    TError,
    void,
    TContext
  >;
  fetch?: RequestInit;
}): CreateMutationResult<
  Awaited<ReturnType<typeof cancelTodayReminder>>,
  TError,
  void,
  TContext
> => {
  const http = inject(HttpClient);
  const cancelTodayReminderMutationOptions = getCancelTodayReminderMutationOptions(http, options);

  return injectMutation(() => cancelTodayReminderMutationOptions);
};
/**
 * @summary Dispara imediatamente o job de standup
 */
export const runReminderNow = (
  http: HttpClient,
  options?: { signal?: AbortSignal | null },
): Promise<TriggerAcceptedDto> => {
  const url = `/reminders/run-now`;
  const request$ = http.post<TriggerAcceptedDto>(url, undefined);
  if (options?.signal) {
    return lastValueFrom(request$.pipe(takeUntil(fromEvent(options.signal, 'abort'))));
  }
  return lastValueFrom(request$);
};

export const getRunReminderNowMutationOptions = <TError = unknown, TContext = unknown>(
  http: HttpClient,
  options?: {
    mutation?: CreateMutationOptions<
      Awaited<ReturnType<typeof runReminderNow>>,
      TError,
      void,
      TContext
    >;
    fetch?: RequestInit;
  },
): CreateMutationOptions<Awaited<ReturnType<typeof runReminderNow>>, TError, void, TContext> => {
  const mutationKey = ['runReminderNow'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof runReminderNow>>, void> = () => {
    return runReminderNow(http, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type RunReminderNowMutationResult = NonNullable<Awaited<ReturnType<typeof runReminderNow>>>;

export type RunReminderNowMutationError = unknown;

/**
 * @summary Dispara imediatamente o job de standup
 */
export const injectRunReminderNow = <TError = unknown, TContext = unknown>(options?: {
  mutation?: CreateMutationOptions<
    Awaited<ReturnType<typeof runReminderNow>>,
    TError,
    void,
    TContext
  >;
  fetch?: RequestInit;
}): CreateMutationResult<Awaited<ReturnType<typeof runReminderNow>>, TError, void, TContext> => {
  const http = inject(HttpClient);
  const runReminderNowMutationOptions = getRunReminderNowMutationOptions(http, options);

  return injectMutation(() => runReminderNowMutationOptions);
};
