/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Standup API
 * API do serviço de geração, revisão e publicação de standups.
 * OpenAPI spec version: 0.0.1
 */
import { HttpClient } from '@angular/common/http';

import { inject } from '@angular/core';

import { QueryClient, injectQuery } from '@tanstack/angular-query-experimental';
import type {
  CreateQueryOptions,
  CreateQueryResult,
  InvalidateOptions,
  QueryFunction,
} from '@tanstack/angular-query-experimental';

import { fromEvent, lastValueFrom } from 'rxjs';

import { takeUntil } from 'rxjs/operators';

import type { RepoListResponseDto } from '../../model';

function filterParams(
  params: Record<string, unknown>,
  requiredNullableKeys: Set<string> = new Set(),
): Record<string, string | number | boolean | Array<string | number | boolean>> {
  const filteredParams: Record<
    string,
    string | number | boolean | null | Array<string | number | boolean>
  > = {};
  for (const [key, value] of Object.entries(params)) {
    if (Array.isArray(value)) {
      const filtered = value.filter(
        (item) =>
          item != null &&
          (typeof item === 'string' || typeof item === 'number' || typeof item === 'boolean'),
      ) as Array<string | number | boolean>;
      if (filtered.length) {
        filteredParams[key] = filtered;
      }
    } else if (value === null && requiredNullableKeys.has(key)) {
      filteredParams[key] = value;
    } else if (
      value != null &&
      (typeof value === 'string' || typeof value === 'number' || typeof value === 'boolean')
    ) {
      filteredParams[key] = value as string | number | boolean;
    }
  }
  return filteredParams as Record<
    string,
    string | number | boolean | Array<string | number | boolean>
  >;
}
/**
 * @summary Lista os repositórios disponíveis para coleta
 */
export const listRepos = (
  http: HttpClient,
  options?: { signal?: AbortSignal | null },
): Promise<RepoListResponseDto> => {
  const url = `/repos`;
  const request$ = http.get<RepoListResponseDto>(url);
  if (options?.signal) {
    return lastValueFrom(request$.pipe(takeUntil(fromEvent(options.signal, 'abort'))));
  }
  return lastValueFrom(request$);
};

export const getListReposQueryKey = () => {
  return [`/repos`] as const;
};

export const getListReposQueryOptions = <
  TData = Awaited<ReturnType<typeof listRepos>>,
  TError = unknown,
>(
  http: HttpClient,
  options?: {
    query?: Partial<CreateQueryOptions<Awaited<ReturnType<typeof listRepos>>, TError, TData>>;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListReposQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listRepos>>> = ({ signal }) =>
    listRepos(http, { signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as CreateQueryOptions<
    Awaited<ReturnType<typeof listRepos>>,
    TError,
    TData
  >;
};

export type ListReposQueryResult = NonNullable<Awaited<ReturnType<typeof listRepos>>>;
export type ListReposQueryError = unknown;

/**
 * @summary Lista os repositórios disponíveis para coleta
 */

export function injectListRepos<TData = Awaited<ReturnType<typeof listRepos>>, TError = unknown>(
  options?:
    | {
        query?: Partial<CreateQueryOptions<Awaited<ReturnType<typeof listRepos>>, TError, TData>>;
        fetch?: RequestInit;
      }
    | (() => {
        query?: Partial<CreateQueryOptions<Awaited<ReturnType<typeof listRepos>>, TError, TData>>;
        fetch?: RequestInit;
      }),
): CreateQueryResult<TData, TError> {
  const http = inject(HttpClient);

  const query = injectQuery(() => {
    // Resolve options if getter function (for signal reactivity)
    const _options = typeof options === 'function' ? options() : options;
    return getListReposQueryOptions(http, _options);
  }) as CreateQueryResult<TData, TError>;

  return query;
}

/**
 * @summary Lista os repositórios disponíveis para coleta
 */
export const invalidateListRepos = async (
  queryClient: QueryClient,
  options?: InvalidateOptions,
): Promise<QueryClient> => {
  await queryClient.invalidateQueries({ queryKey: getListReposQueryKey() }, options);

  return queryClient;
};
