/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Standup API
 * API do serviço de geração, revisão e publicação de standups.
 * OpenAPI spec version: 0.0.1
 */
import { HttpClient, HttpParams } from '@angular/common/http';

import { inject } from '@angular/core';

import { QueryClient, injectMutation, injectQuery } from '@tanstack/angular-query-experimental';
import type {
  CreateMutationOptions,
  CreateMutationResult,
  CreateQueryOptions,
  CreateQueryResult,
  InvalidateOptions,
  MutationFunction,
  MutationFunctionContext,
  QueryFunction,
} from '@tanstack/angular-query-experimental';

import { fromEvent, lastValueFrom } from 'rxjs';

import { takeUntil } from 'rxjs/operators';

import type {
  ApproveStandupDto,
  ApproveStandupResponseDto,
  ListStandupsParams,
  StandupDetailResponseDto,
  StandupListResponseDto,
  TriggerAcceptedDto,
  TriggerStandupDto,
  UpdateStandupStatusDto,
} from '../../model';

function filterParams(
  params: Record<string, unknown>,
  requiredNullableKeys: Set<string> = new Set(),
): Record<string, string | number | boolean | Array<string | number | boolean>> {
  const filteredParams: Record<
    string,
    string | number | boolean | null | Array<string | number | boolean>
  > = {};
  for (const [key, value] of Object.entries(params)) {
    if (Array.isArray(value)) {
      const filtered = value.filter(
        (item) =>
          item != null &&
          (typeof item === 'string' || typeof item === 'number' || typeof item === 'boolean'),
      ) as Array<string | number | boolean>;
      if (filtered.length) {
        filteredParams[key] = filtered;
      }
    } else if (value === null && requiredNullableKeys.has(key)) {
      filteredParams[key] = value;
    } else if (
      value != null &&
      (typeof value === 'string' || typeof value === 'number' || typeof value === 'boolean')
    ) {
      filteredParams[key] = value as string | number | boolean;
    }
  }
  return filteredParams as Record<
    string,
    string | number | boolean | Array<string | number | boolean>
  >;
}
/**
 * @summary Dispara a geração manual de um standup
 */
export const triggerStandup = (
  http: HttpClient,
  triggerStandupDto: TriggerStandupDto,
  options?: { signal?: AbortSignal | null },
): Promise<TriggerAcceptedDto> => {
  const url = `/standups/trigger`;
  const request$ = http.post<TriggerAcceptedDto>(url, triggerStandupDto);
  if (options?.signal) {
    return lastValueFrom(request$.pipe(takeUntil(fromEvent(options.signal, 'abort'))));
  }
  return lastValueFrom(request$);
};

export const getTriggerStandupMutationOptions = <TError = unknown, TContext = unknown>(
  http: HttpClient,
  queryClient: QueryClient,
  options?: {
    mutation?: CreateMutationOptions<
      Awaited<ReturnType<typeof triggerStandup>>,
      TError,
      { data: TriggerStandupDto },
      TContext
    >;
    skipInvalidation?: boolean;
    fetch?: RequestInit;
  },
): CreateMutationOptions<
  Awaited<ReturnType<typeof triggerStandup>>,
  TError,
  { data: TriggerStandupDto },
  TContext
> => {
  const mutationKey = ['triggerStandup'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof triggerStandup>>,
    { data: TriggerStandupDto }
  > = (props) => {
    const { data } = props ?? {};

    return triggerStandup(http, data, fetchOptions);
  };

  const onSuccess = (
    data: Awaited<ReturnType<typeof triggerStandup>>,
    variables: { data: TriggerStandupDto },
    onMutateResult: TContext,
    context: MutationFunctionContext,
  ) => {
    if (!options?.skipInvalidation) {
      queryClient.invalidateQueries({ queryKey: getListStandupsQueryKey() });
    }
    mutationOptions?.onSuccess?.(data, variables, onMutateResult, context);
  };

  return { ...mutationOptions, mutationFn, onSuccess };
};

export type TriggerStandupMutationResult = NonNullable<Awaited<ReturnType<typeof triggerStandup>>>;
export type TriggerStandupMutationBody = TriggerStandupDto;
export type TriggerStandupMutationError = unknown;

/**
 * @summary Dispara a geração manual de um standup
 */
export const injectTriggerStandup = <TError = unknown, TContext = unknown>(options?: {
  mutation?: CreateMutationOptions<
    Awaited<ReturnType<typeof triggerStandup>>,
    TError,
    { data: TriggerStandupDto },
    TContext
  >;
  skipInvalidation?: boolean;
  fetch?: RequestInit;
}): CreateMutationResult<
  Awaited<ReturnType<typeof triggerStandup>>,
  TError,
  { data: TriggerStandupDto },
  TContext
> => {
  const http = inject(HttpClient);
  const queryClient = inject(QueryClient);
  const triggerStandupMutationOptions = getTriggerStandupMutationOptions(
    http,
    queryClient,
    options,
  );

  return injectMutation(() => triggerStandupMutationOptions);
};
/**
 * @summary Abre o stream SSE de eventos de standup
 */
export const streamStandupEvents = (
  http: HttpClient,
  options?: { signal?: AbortSignal | null },
): Promise<void> => {
  const url = `/standups/events`;
  const request$ = http.get<void>(url);
  if (options?.signal) {
    return lastValueFrom(request$.pipe(takeUntil(fromEvent(options.signal, 'abort'))));
  }
  return lastValueFrom(request$);
};

export const getStreamStandupEventsQueryKey = () => {
  return [`/standups/events`] as const;
};

export const getStreamStandupEventsQueryOptions = <
  TData = Awaited<ReturnType<typeof streamStandupEvents>>,
  TError = unknown,
>(
  http: HttpClient,
  options?: {
    query?: Partial<
      CreateQueryOptions<Awaited<ReturnType<typeof streamStandupEvents>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getStreamStandupEventsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof streamStandupEvents>>> = ({ signal }) =>
    streamStandupEvents(http, { signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as CreateQueryOptions<
    Awaited<ReturnType<typeof streamStandupEvents>>,
    TError,
    TData
  >;
};

export type StreamStandupEventsQueryResult = NonNullable<
  Awaited<ReturnType<typeof streamStandupEvents>>
>;
export type StreamStandupEventsQueryError = unknown;

/**
 * @summary Abre o stream SSE de eventos de standup
 */

export function injectStreamStandupEvents<
  TData = Awaited<ReturnType<typeof streamStandupEvents>>,
  TError = unknown,
>(
  options?:
    | {
        query?: Partial<
          CreateQueryOptions<Awaited<ReturnType<typeof streamStandupEvents>>, TError, TData>
        >;
        fetch?: RequestInit;
      }
    | (() => {
        query?: Partial<
          CreateQueryOptions<Awaited<ReturnType<typeof streamStandupEvents>>, TError, TData>
        >;
        fetch?: RequestInit;
      }),
): CreateQueryResult<TData, TError> {
  const http = inject(HttpClient);

  const query = injectQuery(() => {
    // Resolve options if getter function (for signal reactivity)
    const _options = typeof options === 'function' ? options() : options;
    return getStreamStandupEventsQueryOptions(http, _options);
  }) as CreateQueryResult<TData, TError>;

  return query;
}

/**
 * @summary Abre o stream SSE de eventos de standup
 */
export const invalidateStreamStandupEvents = async (
  queryClient: QueryClient,
  options?: InvalidateOptions,
): Promise<QueryClient> => {
  await queryClient.invalidateQueries({ queryKey: getStreamStandupEventsQueryKey() }, options);

  return queryClient;
};

/**
 * @summary Lista standups do usuário autenticado
 */
export const listStandups = (
  http: HttpClient,
  params?: ListStandupsParams,
  options?: { signal?: AbortSignal | null },
): Promise<StandupListResponseDto> => {
  const httpParams = params
    ? new HttpParams({ fromObject: filterParams(params, new Set<string>([])) })
    : undefined;
  const url = `/standups`;
  const request$ = http.get<StandupListResponseDto>(url, { params: httpParams });
  if (options?.signal) {
    return lastValueFrom(request$.pipe(takeUntil(fromEvent(options.signal, 'abort'))));
  }
  return lastValueFrom(request$);
};

export const getListStandupsQueryKey = (params?: ListStandupsParams) => {
  return [`/standups`, ...(params ? [params] : [])] as const;
};

export const getListStandupsQueryOptions = <
  TData = Awaited<ReturnType<typeof listStandups>>,
  TError = unknown,
>(
  http: HttpClient,
  params?: ListStandupsParams,
  options?: {
    query?: Partial<CreateQueryOptions<Awaited<ReturnType<typeof listStandups>>, TError, TData>>;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListStandupsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listStandups>>> = ({ signal }) =>
    listStandups(http, params, { signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as CreateQueryOptions<
    Awaited<ReturnType<typeof listStandups>>,
    TError,
    TData
  >;
};

export type ListStandupsQueryResult = NonNullable<Awaited<ReturnType<typeof listStandups>>>;
export type ListStandupsQueryError = unknown;

/**
 * @summary Lista standups do usuário autenticado
 */

export function injectListStandups<
  TData = Awaited<ReturnType<typeof listStandups>>,
  TError = unknown,
>(
  params?: ListStandupsParams | (() => ListStandupsParams | undefined),
  options?:
    | {
        query?: Partial<
          CreateQueryOptions<Awaited<ReturnType<typeof listStandups>>, TError, TData>
        >;
        fetch?: RequestInit;
      }
    | (() => {
        query?: Partial<
          CreateQueryOptions<Awaited<ReturnType<typeof listStandups>>, TError, TData>
        >;
        fetch?: RequestInit;
      }),
): CreateQueryResult<TData, TError> {
  const http = inject(HttpClient);

  const query = injectQuery(() => {
    // Resolve params if getter function (for signal reactivity)
    const _params = typeof params === 'function' ? params() : params;
    // Resolve options if getter function (for signal reactivity)
    const _options = typeof options === 'function' ? options() : options;
    return getListStandupsQueryOptions(http, _params, _options);
  }) as CreateQueryResult<TData, TError>;

  return query;
}

/**
 * @summary Lista standups do usuário autenticado
 */
export const invalidateListStandups = async (
  queryClient: QueryClient,
  params?: ListStandupsParams,
  options?: InvalidateOptions,
): Promise<QueryClient> => {
  await queryClient.invalidateQueries({ queryKey: getListStandupsQueryKey(params) }, options);

  return queryClient;
};

/**
 * @summary Busca um standup pelo identificador
 */
export const getStandupById = (
  http: HttpClient,
  id: string,
  options?: { signal?: AbortSignal | null },
): Promise<StandupDetailResponseDto> => {
  const url = `/standups/${id}`;
  const request$ = http.get<StandupDetailResponseDto>(url);
  if (options?.signal) {
    return lastValueFrom(request$.pipe(takeUntil(fromEvent(options.signal, 'abort'))));
  }
  return lastValueFrom(request$);
};

export const getGetStandupByIdQueryKey = (id: string) => {
  return [`/standups/${id}`] as const;
};

export const getGetStandupByIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getStandupById>>,
  TError = unknown,
>(
  http: HttpClient,
  id: string,
  options?: {
    query?: Partial<CreateQueryOptions<Awaited<ReturnType<typeof getStandupById>>, TError, TData>>;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetStandupByIdQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getStandupById>>> = ({ signal }) =>
    getStandupById(http, id, { signal, ...fetchOptions });

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as CreateQueryOptions<
    Awaited<ReturnType<typeof getStandupById>>,
    TError,
    TData
  >;
};

export type GetStandupByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getStandupById>>>;
export type GetStandupByIdQueryError = unknown;

/**
 * @summary Busca um standup pelo identificador
 */

export function injectGetStandupById<
  TData = Awaited<ReturnType<typeof getStandupById>>,
  TError = unknown,
>(
  id: string | (() => string),
  options?:
    | {
        query?: Partial<
          CreateQueryOptions<Awaited<ReturnType<typeof getStandupById>>, TError, TData>
        >;
        fetch?: RequestInit;
      }
    | (() => {
        query?: Partial<
          CreateQueryOptions<Awaited<ReturnType<typeof getStandupById>>, TError, TData>
        >;
        fetch?: RequestInit;
      }),
): CreateQueryResult<TData, TError> {
  const http = inject(HttpClient);

  const query = injectQuery(() => {
    // Resolve params if getter function (for signal reactivity)
    const _id = typeof id === 'function' ? id() : id;
    // Resolve options if getter function (for signal reactivity)
    const _options = typeof options === 'function' ? options() : options;
    return getGetStandupByIdQueryOptions(http, _id, _options);
  }) as CreateQueryResult<TData, TError>;

  return query;
}

/**
 * @summary Busca um standup pelo identificador
 */
export const invalidateGetStandupById = async (
  queryClient: QueryClient,
  id: string,
  options?: InvalidateOptions,
): Promise<QueryClient> => {
  await queryClient.invalidateQueries({ queryKey: getGetStandupByIdQueryKey(id) }, options);

  return queryClient;
};

/**
 * @summary Atualiza o status de um standup
 */
export const updateStandupStatus = (
  http: HttpClient,
  id: string,
  updateStandupStatusDto: UpdateStandupStatusDto,
  options?: { signal?: AbortSignal | null },
): Promise<StandupDetailResponseDto> => {
  const url = `/standups/${id}/status`;
  const request$ = http.patch<StandupDetailResponseDto>(url, updateStandupStatusDto);
  if (options?.signal) {
    return lastValueFrom(request$.pipe(takeUntil(fromEvent(options.signal, 'abort'))));
  }
  return lastValueFrom(request$);
};

export const getUpdateStandupStatusMutationOptions = <TError = unknown, TContext = unknown>(
  http: HttpClient,
  queryClient: QueryClient,
  options?: {
    mutation?: CreateMutationOptions<
      Awaited<ReturnType<typeof updateStandupStatus>>,
      TError,
      { id: string; data: UpdateStandupStatusDto },
      TContext
    >;
    skipInvalidation?: boolean;
    fetch?: RequestInit;
  },
): CreateMutationOptions<
  Awaited<ReturnType<typeof updateStandupStatus>>,
  TError,
  { id: string; data: UpdateStandupStatusDto },
  TContext
> => {
  const mutationKey = ['updateStandupStatus'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateStandupStatus>>,
    { id: string; data: UpdateStandupStatusDto }
  > = (props) => {
    const { id, data } = props ?? {};

    return updateStandupStatus(http, id, data, fetchOptions);
  };

  const onSuccess = (
    data: Awaited<ReturnType<typeof updateStandupStatus>>,
    variables: { id: string; data: UpdateStandupStatusDto },
    onMutateResult: TContext,
    context: MutationFunctionContext,
  ) => {
    if (!options?.skipInvalidation) {
      queryClient.invalidateQueries({ queryKey: getListStandupsQueryKey() });
      queryClient.invalidateQueries({ queryKey: getGetStandupByIdQueryKey(variables.id) });
    }
    mutationOptions?.onSuccess?.(data, variables, onMutateResult, context);
  };

  return { ...mutationOptions, mutationFn, onSuccess };
};

export type UpdateStandupStatusMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateStandupStatus>>
>;
export type UpdateStandupStatusMutationBody = UpdateStandupStatusDto;
export type UpdateStandupStatusMutationError = unknown;

/**
 * @summary Atualiza o status de um standup
 */
export const injectUpdateStandupStatus = <TError = unknown, TContext = unknown>(options?: {
  mutation?: CreateMutationOptions<
    Awaited<ReturnType<typeof updateStandupStatus>>,
    TError,
    { id: string; data: UpdateStandupStatusDto },
    TContext
  >;
  skipInvalidation?: boolean;
  fetch?: RequestInit;
}): CreateMutationResult<
  Awaited<ReturnType<typeof updateStandupStatus>>,
  TError,
  { id: string; data: UpdateStandupStatusDto },
  TContext
> => {
  const http = inject(HttpClient);
  const queryClient = inject(QueryClient);
  const updateStandupStatusMutationOptions = getUpdateStandupStatusMutationOptions(
    http,
    queryClient,
    options,
  );

  return injectMutation(() => updateStandupStatusMutationOptions);
};
/**
 * @summary Aprova um standup pendente
 */
export const approveStandup = (
  http: HttpClient,
  id: string,
  approveStandupDto: ApproveStandupDto,
  options?: { signal?: AbortSignal | null },
): Promise<ApproveStandupResponseDto> => {
  const url = `/standups/${id}/approve`;
  const request$ = http.post<ApproveStandupResponseDto>(url, approveStandupDto);
  if (options?.signal) {
    return lastValueFrom(request$.pipe(takeUntil(fromEvent(options.signal, 'abort'))));
  }
  return lastValueFrom(request$);
};

export const getApproveStandupMutationOptions = <TError = unknown, TContext = unknown>(
  http: HttpClient,
  queryClient: QueryClient,
  options?: {
    mutation?: CreateMutationOptions<
      Awaited<ReturnType<typeof approveStandup>>,
      TError,
      { id: string; data: ApproveStandupDto },
      TContext
    >;
    skipInvalidation?: boolean;
    fetch?: RequestInit;
  },
): CreateMutationOptions<
  Awaited<ReturnType<typeof approveStandup>>,
  TError,
  { id: string; data: ApproveStandupDto },
  TContext
> => {
  const mutationKey = ['approveStandup'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof approveStandup>>,
    { id: string; data: ApproveStandupDto }
  > = (props) => {
    const { id, data } = props ?? {};

    return approveStandup(http, id, data, fetchOptions);
  };

  const onSuccess = (
    data: Awaited<ReturnType<typeof approveStandup>>,
    variables: { id: string; data: ApproveStandupDto },
    onMutateResult: TContext,
    context: MutationFunctionContext,
  ) => {
    if (!options?.skipInvalidation) {
      queryClient.invalidateQueries({ queryKey: getListStandupsQueryKey() });
      queryClient.invalidateQueries({ queryKey: getGetStandupByIdQueryKey(variables.id) });
    }
    mutationOptions?.onSuccess?.(data, variables, onMutateResult, context);
  };

  return { ...mutationOptions, mutationFn, onSuccess };
};

export type ApproveStandupMutationResult = NonNullable<Awaited<ReturnType<typeof approveStandup>>>;
export type ApproveStandupMutationBody = ApproveStandupDto;
export type ApproveStandupMutationError = unknown;

/**
 * @summary Aprova um standup pendente
 */
export const injectApproveStandup = <TError = unknown, TContext = unknown>(options?: {
  mutation?: CreateMutationOptions<
    Awaited<ReturnType<typeof approveStandup>>,
    TError,
    { id: string; data: ApproveStandupDto },
    TContext
  >;
  skipInvalidation?: boolean;
  fetch?: RequestInit;
}): CreateMutationResult<
  Awaited<ReturnType<typeof approveStandup>>,
  TError,
  { id: string; data: ApproveStandupDto },
  TContext
> => {
  const http = inject(HttpClient);
  const queryClient = inject(QueryClient);
  const approveStandupMutationOptions = getApproveStandupMutationOptions(
    http,
    queryClient,
    options,
  );

  return injectMutation(() => approveStandupMutationOptions);
};
/**
 * @summary Envia standup aprovado para o Discord via automacao
 */
export const sendToDiscord = (
  http: HttpClient,
  id: string,
  options?: { signal?: AbortSignal | null },
): Promise<StandupDetailResponseDto> => {
  const url = `/standups/${id}/send-to-discord`;
  const request$ = http.post<StandupDetailResponseDto>(url, undefined);
  if (options?.signal) {
    return lastValueFrom(request$.pipe(takeUntil(fromEvent(options.signal, 'abort'))));
  }
  return lastValueFrom(request$);
};

export const getSendToDiscordMutationOptions = <TError = unknown, TContext = unknown>(
  http: HttpClient,
  queryClient: QueryClient,
  options?: {
    mutation?: CreateMutationOptions<
      Awaited<ReturnType<typeof sendToDiscord>>,
      TError,
      { id: string },
      TContext
    >;
    skipInvalidation?: boolean;
    fetch?: RequestInit;
  },
): CreateMutationOptions<
  Awaited<ReturnType<typeof sendToDiscord>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ['sendToDiscord'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof sendToDiscord>>, { id: string }> = (
    props,
  ) => {
    const { id } = props ?? {};

    return sendToDiscord(http, id, fetchOptions);
  };

  const onSuccess = (
    data: Awaited<ReturnType<typeof sendToDiscord>>,
    variables: { id: string },
    onMutateResult: TContext,
    context: MutationFunctionContext,
  ) => {
    if (!options?.skipInvalidation) {
      queryClient.invalidateQueries({ queryKey: getListStandupsQueryKey() });
      queryClient.invalidateQueries({ queryKey: getGetStandupByIdQueryKey(variables.id) });
    }
    mutationOptions?.onSuccess?.(data, variables, onMutateResult, context);
  };

  return { ...mutationOptions, mutationFn, onSuccess };
};

export type SendToDiscordMutationResult = NonNullable<Awaited<ReturnType<typeof sendToDiscord>>>;

export type SendToDiscordMutationError = unknown;

/**
 * @summary Envia standup aprovado para o Discord via automacao
 */
export const injectSendToDiscord = <TError = unknown, TContext = unknown>(options?: {
  mutation?: CreateMutationOptions<
    Awaited<ReturnType<typeof sendToDiscord>>,
    TError,
    { id: string },
    TContext
  >;
  skipInvalidation?: boolean;
  fetch?: RequestInit;
}): CreateMutationResult<
  Awaited<ReturnType<typeof sendToDiscord>>,
  TError,
  { id: string },
  TContext
> => {
  const http = inject(HttpClient);
  const queryClient = inject(QueryClient);
  const sendToDiscordMutationOptions = getSendToDiscordMutationOptions(http, queryClient, options);

  return injectMutation(() => sendToDiscordMutationOptions);
};
