/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Standup API
 * API do serviço de geração, revisão e publicação de standups.
 * OpenAPI spec version: 0.0.1
 */
import { HttpClient } from '@angular/common/http';

import { inject } from '@angular/core';

import { QueryClient, injectMutation, injectQuery } from '@tanstack/angular-query-experimental';
import type {
  CreateMutationOptions,
  CreateMutationResult,
  CreateQueryOptions,
  CreateQueryResult,
  InvalidateOptions,
  MutationFunction,
  MutationFunctionContext,
  QueryFunction,
} from '@tanstack/angular-query-experimental';

import { fromEvent, lastValueFrom } from 'rxjs';

import { takeUntil } from 'rxjs/operators';

import type { MeSettingsResponseDto, PutMeSettingsDto } from '../../model';

function filterParams(
  params: Record<string, unknown>,
  requiredNullableKeys: Set<string> = new Set(),
): Record<string, string | number | boolean | Array<string | number | boolean>> {
  const filteredParams: Record<
    string,
    string | number | boolean | null | Array<string | number | boolean>
  > = {};
  for (const [key, value] of Object.entries(params)) {
    if (Array.isArray(value)) {
      const filtered = value.filter(
        (item) =>
          item != null &&
          (typeof item === 'string' || typeof item === 'number' || typeof item === 'boolean'),
      ) as Array<string | number | boolean>;
      if (filtered.length) {
        filteredParams[key] = filtered;
      }
    } else if (value === null && requiredNullableKeys.has(key)) {
      filteredParams[key] = value;
    } else if (
      value != null &&
      (typeof value === 'string' || typeof value === 'number' || typeof value === 'boolean')
    ) {
      filteredParams[key] = value as string | number | boolean;
    }
  }
  return filteredParams as Record<
    string,
    string | number | boolean | Array<string | number | boolean>
  >;
}
/**
 * @summary Consulta as configurações do usuário autenticado
 */
export const getMeSettings = (
  http: HttpClient,
  options?: { signal?: AbortSignal | null },
): Promise<MeSettingsResponseDto> => {
  const url = `/settings/me`;
  const request$ = http.get<MeSettingsResponseDto>(url);
  if (options?.signal) {
    return lastValueFrom(request$.pipe(takeUntil(fromEvent(options.signal, 'abort'))));
  }
  return lastValueFrom(request$);
};

export const getGetMeSettingsQueryKey = () => {
  return [`/settings/me`] as const;
};

export const getGetMeSettingsQueryOptions = <
  TData = Awaited<ReturnType<typeof getMeSettings>>,
  TError = unknown,
>(
  http: HttpClient,
  options?: {
    query?: Partial<CreateQueryOptions<Awaited<ReturnType<typeof getMeSettings>>, TError, TData>>;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetMeSettingsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getMeSettings>>> = ({ signal }) =>
    getMeSettings(http, { signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as CreateQueryOptions<
    Awaited<ReturnType<typeof getMeSettings>>,
    TError,
    TData
  >;
};

export type GetMeSettingsQueryResult = NonNullable<Awaited<ReturnType<typeof getMeSettings>>>;
export type GetMeSettingsQueryError = unknown;

/**
 * @summary Consulta as configurações do usuário autenticado
 */

export function injectGetMeSettings<
  TData = Awaited<ReturnType<typeof getMeSettings>>,
  TError = unknown,
>(
  options?:
    | {
        query?: Partial<
          CreateQueryOptions<Awaited<ReturnType<typeof getMeSettings>>, TError, TData>
        >;
        fetch?: RequestInit;
      }
    | (() => {
        query?: Partial<
          CreateQueryOptions<Awaited<ReturnType<typeof getMeSettings>>, TError, TData>
        >;
        fetch?: RequestInit;
      }),
): CreateQueryResult<TData, TError> {
  const http = inject(HttpClient);

  const query = injectQuery(() => {
    // Resolve options if getter function (for signal reactivity)
    const _options = typeof options === 'function' ? options() : options;
    return getGetMeSettingsQueryOptions(http, _options);
  }) as CreateQueryResult<TData, TError>;

  return query;
}

/**
 * @summary Consulta as configurações do usuário autenticado
 */
export const invalidateGetMeSettings = async (
  queryClient: QueryClient,
  options?: InvalidateOptions,
): Promise<QueryClient> => {
  await queryClient.invalidateQueries({ queryKey: getGetMeSettingsQueryKey() }, options);

  return queryClient;
};

/**
 * @summary Atualiza as configurações do usuário autenticado
 */
export const updateMeSettings = (
  http: HttpClient,
  putMeSettingsDto: PutMeSettingsDto,
  options?: { signal?: AbortSignal | null },
): Promise<MeSettingsResponseDto> => {
  const url = `/settings/me`;
  const request$ = http.put<MeSettingsResponseDto>(url, putMeSettingsDto);
  if (options?.signal) {
    return lastValueFrom(request$.pipe(takeUntil(fromEvent(options.signal, 'abort'))));
  }
  return lastValueFrom(request$);
};

export const getUpdateMeSettingsMutationOptions = <TError = unknown, TContext = unknown>(
  http: HttpClient,
  queryClient: QueryClient,
  options?: {
    mutation?: CreateMutationOptions<
      Awaited<ReturnType<typeof updateMeSettings>>,
      TError,
      { data: PutMeSettingsDto },
      TContext
    >;
    skipInvalidation?: boolean;
    fetch?: RequestInit;
  },
): CreateMutationOptions<
  Awaited<ReturnType<typeof updateMeSettings>>,
  TError,
  { data: PutMeSettingsDto },
  TContext
> => {
  const mutationKey = ['updateMeSettings'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateMeSettings>>,
    { data: PutMeSettingsDto }
  > = (props) => {
    const { data } = props ?? {};

    return updateMeSettings(http, data, fetchOptions);
  };

  const onSuccess = (
    data: Awaited<ReturnType<typeof updateMeSettings>>,
    variables: { data: PutMeSettingsDto },
    onMutateResult: TContext,
    context: MutationFunctionContext,
  ) => {
    if (!options?.skipInvalidation) {
      queryClient.invalidateQueries({ queryKey: getGetMeSettingsQueryKey() });
    }
    mutationOptions?.onSuccess?.(data, variables, onMutateResult, context);
  };

  return { ...mutationOptions, mutationFn, onSuccess };
};

export type UpdateMeSettingsMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateMeSettings>>
>;
export type UpdateMeSettingsMutationBody = PutMeSettingsDto;
export type UpdateMeSettingsMutationError = unknown;

/**
 * @summary Atualiza as configurações do usuário autenticado
 */
export const injectUpdateMeSettings = <TError = unknown, TContext = unknown>(options?: {
  mutation?: CreateMutationOptions<
    Awaited<ReturnType<typeof updateMeSettings>>,
    TError,
    { data: PutMeSettingsDto },
    TContext
  >;
  skipInvalidation?: boolean;
  fetch?: RequestInit;
}): CreateMutationResult<
  Awaited<ReturnType<typeof updateMeSettings>>,
  TError,
  { data: PutMeSettingsDto },
  TContext
> => {
  const http = inject(HttpClient);
  const queryClient = inject(QueryClient);
  const updateMeSettingsMutationOptions = getUpdateMeSettingsMutationOptions(
    http,
    queryClient,
    options,
  );

  return injectMutation(() => updateMeSettingsMutationOptions);
};
