/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Standup API
 * API do serviço de geração, revisão e publicação de standups.
 * OpenAPI spec version: 0.0.1
 */

export type ListStandupsSort = (typeof ListStandupsSort)[keyof typeof ListStandupsSort];

export const ListStandupsSort = {
  date: 'date',
  createdAt: 'createdAt',
  status: 'status',
} as const;
