/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Standup API
 * API do serviço de geração, revisão e publicação de standups.
 * OpenAPI spec version: 0.0.1
 */
import type { ListStandupsStatus } from './listStandupsStatus';

export type ListStandupsParams = {
  date?: string;
  from?: string;
  to?: string;
  search?: string;
  page?: number;
  pageSize?: number;
  status?: ListStandupsStatus;
};
