/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Standup API
 * API do serviço de geração, revisão e publicação de standups.
 * OpenAPI spec version: 0.0.1
 */
import type { MeSettingsRecordDtoEmailTheme } from './meSettingsRecordDtoEmailTheme';

export interface MeSettingsRecordDto {
  standupCron: string;
  reminderCron: string;
  recoveryCron: string;
  timezone: string;
  gitAuthor: string;
  gitSincePeriod: string;
  selectedRepos: string[];
  active: boolean;
  emailTheme: MeSettingsRecordDtoEmailTheme;
  /** @nullable */
  snoozedUntil?: number | null;
  /** @nullable */
  cancelledDate?: string | null;
  /** @nullable */
  azureDevopsUser?: string | null;
}
