/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Standup API
 * API do serviço de geração, revisão e publicação de standups.
 * OpenAPI spec version: 0.0.1
 */
import type { PutMeSettingsDtoEmailTheme } from './putMeSettingsDtoEmailTheme'

export interface PutMeSettingsDto {
  standupCron: string
  reminderCron: string
  recoveryCron: string
  timezone: string
  gitAuthor?: string
  gitSincePeriod?: string
  selectedRepos?: string[]
  active?: boolean
  emailTheme?: PutMeSettingsDtoEmailTheme
  azureDevopsUser?: string
}
