/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Standup API
 * API do serviço de geração, revisão e publicação de standups.
 * OpenAPI spec version: 0.0.1
 */
import type { PaginationDto } from './paginationDto';
import type { StandupRecordDto } from './standupRecordDto';
import type { SummaryDto } from './summaryDto';

export interface StandupListResponseDto {
  data: StandupRecordDto[];
  pagination: PaginationDto;
  summary: SummaryDto;
}
