/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Standup API
 * API do serviço de geração, revisão e publicação de standups.
 * OpenAPI spec version: 0.0.1
 */
import type { CustomEntriesDto } from './customEntriesDto';
import type { StandupRecordDtoStatus } from './standupRecordDtoStatus';

export interface StandupRecordDto {
  id: string;
  date: string;
  meetingType: string;
  content: string;
  sourceData: string;
  customEntries?: CustomEntriesDto | null;
  status: StandupRecordDtoStatus;
  /** @nullable */
  userId?: string | null;
  /** @nullable */
  dmMessageId?: string | null;
  createdAt: number;
  updatedAt: number;
  /** @nullable */
  sentToDiscordAt?: number | null;
}
