/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Standup API
 * API do serviço de geração, revisão e publicação de standups.
 * OpenAPI spec version: 0.0.1
 */

export interface TriggerStandupDto {
  extraContext?: string;
  forceRegenerate?: boolean;
  rewriteFromStandupId?: string;
  rewriteInstruction?: string;
  replaceStandupId?: string;
}
