name: Publish Install Script to Gist

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish-gist:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Update install script in Gist
        env:
          GIST_TOKEN: ${{ secrets.GIST_TOKEN }}
          GIST_ID: ${{ secrets.GIST_ID }}
        run: |
          FILE="scripts/install-standup.sh"
          GIST_FILENAME="install-standup.sh"

          if [ ! -f "$FILE" ]; then
            echo "❌ Arquivo $FILE não encontrado."
            exit 1
          fi

          echo "🚀 Atualizando Gist (ID: $GIST_ID) com $FILE ..."

          CONTENT=$(jq -Rs . < "$FILE") # transforma o script em string JSON segura

          RESPONSE=$(curl -s -L \
            -X PATCH \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GIST_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/gists/$GIST_ID \
            -d "{
                  \"description\": \"Install script for Standup (auto-updated on push to main)\",
                  \"files\": {\"$GIST_FILENAME\": {\"content\": $CONTENT}}
                }"
          )

          GIST_URL=$(echo "$RESPONSE" | jq -r '.html_url')
          if [ "$GIST_URL" = "null" ] || [ -z "$GIST_URL" ]; then
            echo "❌ Falha ao atualizar o Gist:"
            echo "$RESPONSE"
            exit 1
          fi

          echo "✅ Gist atualizado com sucesso!"
          echo "🌐 URL público do script: $GIST_URL"
